apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-standalone
  labels:
    app: nginx-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-standalone
  template:
    metadata:
      labels:
        app: nginx-standalone
    spec:
      containers:
      - image: nginx:alpine
        name: nginx-standalone
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"