apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
  namespace: default
spec:
    containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
      - containerPort: 80
      resources: